Repository AY2122S1-CS2103-F10-4/tp, pull requests merged in 2021-10, with the labels that each got.

#28 Myron policy storage
  src/main/java/seedu/siasa/MainApp.java
  src/main/java/seedu/siasa/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/siasa/model/UserPrefs.java
  src/main/java/seedu/siasa/storage/JsonAdaptedPolicy.java
  src/main/java/seedu/siasa/storage/JsonPolicyBookStorage.java
  src/main/java/seedu/siasa/storage/JsonSerializablePolicyBook.java
  src/main/java/seedu/siasa/storage/PolicyBookStorage.java
  src/main/java/seedu/siasa/storage/Storage.java
  src/main/java/seedu/siasa/storage/StorageManager.java
  src/test/java/seedu/siasa/logic/LogicManagerTest.java
  src/test/java/seedu/siasa/storage/StorageManagerTest.java
Labels: priority.Medium

#30 Fix UI component to display policies properly
  src/main/java/seedu/siasa/model/policy/Price.java
  src/main/java/seedu/siasa/ui/PolicyCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PolicyListCard.fxml
Labels: type.Task, priority.Medium

#44 Refactor storage test and update UI class diagram
  docs/diagrams/UiClassDiagram.puml
  src/test/java/seedu/siasa/logic/LogicManagerTest.java
Labels: type.Task
