Repository AY2122S1-CS2103-F10-4/tp, pull requests merged in 2021-11, with the labels that each got.

#135 Fix typo in EditPolicyCommand.java
  src/main/java/seedu/siasa/logic/commands/policy/EditPolicyCommand.java
Labels: bug

#137 Fix sorting not working after modifying lists
  src/main/java/seedu/siasa/logic/commands/contact/SortContactCommand.java
  src/main/java/seedu/siasa/logic/parser/contact/SortContactCommandParser.java
  src/main/java/seedu/siasa/model/ModelManager.java
Labels: bug

#141 Fix `expiringpolicy` command
  src/main/java/seedu/siasa/logic/commands/contact/FindContactCommand.java
  src/main/java/seedu/siasa/logic/commands/policy/ShowExpiringPolicyCommand.java
  src/main/java/seedu/siasa/logic/commands/policy/ShowExpiringPolicySummaryCommand.java
  src/main/java/seedu/siasa/logic/parser/SiasaParser.java
  src/main/java/seedu/siasa/logic/parser/contact/FindCommandParser.java
  src/main/java/seedu/siasa/ui/MainWindow.java
  src/test/java/seedu/siasa/logic/commands/FindContactCommandTest.java
  src/test/java/seedu/siasa/logic/parser/FindContactCommandParserTest.java
  src/test/java/seedu/siasa/logic/parser/SiasaParserTest.java
Labels: bug

#143 Zhuoyang fix warning
  src/main/java/seedu/siasa/ui/WarningWindow.java
  src/main/resources/view/WarningWindow.fxml
Labels: bug

#146 Zhuoyang fix download stats
  src/main/java/seedu/siasa/commons/util/StringUtil.java
  src/main/java/seedu/siasa/logic/commands/DownloadCommand.java
  src/main/java/seedu/siasa/model/Model.java
  src/main/java/seedu/siasa/model/ModelManager.java
  src/main/java/seedu/siasa/model/Siasa.java
  src/test/java/seedu/siasa/logic/commands/contact/AddContactCommandTest.java
Labels: bug

#140 Fix t/ prefix not working for `editpolicy` command
  src/main/java/seedu/siasa/logic/parser/contact/EditContactCommandParser.java
  src/main/java/seedu/siasa/logic/parser/policy/EditPolicyCommandParser.java
Labels: bug

#145 Myron ped readme fixes
  docs/UserGuide.md
  src/main/java/seedu/siasa/ui/GuideWindow.java
Labels: bug

#149 Fix exceptions due to FilteredList
  src/main/java/seedu/siasa/model/ModelManager.java
Labels: bug

#148 Zhuoyang code quality improvements warning stats
  src/main/java/seedu/siasa/logic/commands/DownloadCommand.java
  src/main/java/seedu/siasa/logic/commands/Warning.java
  src/main/java/seedu/siasa/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/siasa/logic/commands/policy/AddPolicyCommand.java
  src/main/java/seedu/siasa/logic/commands/policy/EditPolicyCommand.java
  src/main/java/seedu/siasa/model/Siasa.java
  src/main/java/seedu/siasa/ui/MainWindow.java
  src/main/java/seedu/siasa/ui/WarningWindow.java
  src/test/java/seedu/siasa/model/policy/CoverageExpiryDateTest.java
Labels: bug

#152 Rename list commands to be more intuitive
  docs/UserGuide.md
  src/main/java/seedu/siasa/logic/commands/contact/ListContactCommand.java
  src/main/java/seedu/siasa/logic/commands/policy/ListPolicyCommand.java
Labels: enhancement

#156 Fix incorrect response result for `sortcontact` command
  src/main/java/seedu/siasa/logic/commands/contact/SortContactCommand.java
  src/main/java/seedu/siasa/logic/commands/policy/SortPolicyCommand.java
Labels: bug

#191 Initial write-up for sorting and filtering
  docs/DeveloperGuide.md
Labels: documentation

#193 Fixed formatting
  docs/DeveloperGuide.md
Labels: documentation

#192 Fix `editcontact` bug.
  src/main/java/seedu/siasa/logic/commands/contact/EditContactCommand.java
  src/main/java/seedu/siasa/logic/parser/contact/EditContactCommandParser.java
  src/main/java/seedu/siasa/logic/parser/policy/EditPolicyCommandParser.java
  src/main/java/seedu/siasa/model/Model.java
  src/main/java/seedu/siasa/model/ModelManager.java
  src/main/java/seedu/siasa/model/Siasa.java
  src/test/java/seedu/siasa/logic/commands/contact/AddContactCommandTest.java
  src/test/java/seedu/siasa/logic/commands/contact/EditContactCommandTest.java
Labels: bug

#201 Yatbun Developer Guide Changes
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/SortPolicyDscSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/SortPolicyDscSequenceDiagram.png
Labels: documentation

#202 Increased the size of logic diagram
  docs/DeveloperGuide.md
Labels: documentation

#214 Fix some DG errors
  docs/DeveloperGuide.md
Labels: documentation

#216 Myron ppp
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/meerian.md
Labels: documentation

#220 Add PR links to the PPP
  docs/AboutUs.md
  docs/team/meerian.md
Labels: documentation

#222 Fix print header
  docs/_sass/minima/_base.scss
Labels: bug, documentation

#224 Increased Logic Diagram font size, deleted incorrect diagram
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.png
  docs/images/LogicClassDiagram.png
Labels: documentation

#225 Sherwin fix policy details typos
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/sherwinprofile.jpg
Labels: documentation

#227 Fix DeleteSequenceDiagram
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: bug, documentation
